name: Junit Dryrun

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Unit Test
        run: mvn test

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test_Report
          path: target/cucumber-report.html

